"""initial_schema_v2

Revision ID: 1deb8d6cacfd
Revises:
Create Date: 2026-07-02 12:50:52.959651

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1deb8d6cacfd'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('parent_run_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('reasoning_summary', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('running', 'success', 'error', name='agent_run_status'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_runs_agent_name_status', 'agent_runs', ['agent_name', 'status'], unique=False)
    op.create_index('ix_agent_runs_session_id', 'agent_runs', ['session_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('actor_id', sa.String(length=100), nullable=True),
    sa.Column('actor_type', sa.Enum('user', 'agent', 'system', name='actor_type'), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('diff', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_actor', 'audit_log', ['actor_type', 'actor_id'], unique=False)
    op.create_index('ix_audit_log_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_table('demo_users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('operator', 'supervisor', 'maintenance_manager', 'plant_director',
                              'ai_engineer', name='demo_user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plants',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('platform_config',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('agent_evaluations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('agent_run_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('groundedness', sa.Float(), nullable=True),
    sa.Column('hallucination_flag', sa.Boolean(), nullable=False),
    sa.Column('tool_success_rate', sa.Float(), nullable=True),
    sa.Column('evaluator', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_evaluations_agent_run_id'), 'agent_evaluations', ['agent_run_id'], unique=False)
    op.create_table('lines',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('plant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('rag_queries',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('agent_run_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('top_k', sa.Integer(), nullable=False),
    sa.Column('retrieval_latency_ms', sa.Integer(), nullable=True),
    sa.Column('avg_similarity', sa.Float(), nullable=True),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hit', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_queries_agent_run_id'), 'rag_queries', ['agent_run_id'], unique=False)
    op.create_table('tool_calls',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('agent_run_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('success', 'error', name='tool_call_status'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tool_calls_agent_run_id', 'tool_calls', ['agent_run_id'], unique=False)
    op.create_table('machines',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('machine_type', sa.String(length=50), nullable=False),
    sa.Column('line_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('status', sa.Enum('healthy', 'warning', 'critical', name='machine_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('model_predictions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('machine_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('prediction', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('shap_top_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_model_predictions_machine_created', 'model_predictions',
                    ['machine_id', 'created_at'], unique=False)
    op.create_table('timeline_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('machine_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.Enum('sensor_anomaly', 'prediction', 'agent_decision', 'rca', 'economic',
                              'wo_created', 'alert_created', 'alert_resolved',
                              name='timeline_event_kind'), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_timeline_events_machine_ts', 'timeline_events', ['machine_id', 'ts'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('machine_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', name='alert_severity'), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('new', 'acknowledged', 'assigned', 'resolved', name='alert_status'), nullable=False),
    sa.Column('acknowledged_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('assigned_to', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prediction_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('work_order_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['demo_users.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['demo_users.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['model_predictions.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_machine_id', 'alerts', ['machine_id'], unique=False)
    op.create_index('ix_alerts_status_severity', 'alerts', ['status', 'severity'], unique=False)
    op.create_table('work_orders',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('machine_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('alert_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('critical', 'high', 'medium', 'low', name='wo_priority'), nullable=False),
    sa.Column('status', sa.Enum('open', 'assigned', 'in_progress', 'completed', name='wo_status'), nullable=False),
    sa.Column('assigned_to', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('created_by_agent_run_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['demo_users.id'], ),
    sa.ForeignKeyConstraint(['created_by_agent_run_id'], ['agent_runs.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_orders')
    op.drop_index('ix_alerts_status_severity', table_name='alerts')
    op.drop_index('ix_alerts_machine_id', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_timeline_events_machine_ts', table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index('ix_model_predictions_machine_created', table_name='model_predictions')
    op.drop_table('model_predictions')
    op.drop_table('machines')
    op.drop_index('ix_tool_calls_agent_run_id', table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index(op.f('ix_rag_queries_agent_run_id'), table_name='rag_queries')
    op.drop_table('rag_queries')
    op.drop_table('lines')
    op.drop_index(op.f('ix_agent_evaluations_agent_run_id'), table_name='agent_evaluations')
    op.drop_table('agent_evaluations')
    op.drop_table('platform_config')
    op.drop_table('plants')
    op.drop_table('demo_users')
    op.drop_index('ix_audit_log_entity', table_name='audit_log')
    op.drop_index('ix_audit_log_actor', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_agent_runs_session_id', table_name='agent_runs')
    op.drop_index('ix_agent_runs_agent_name_status', table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
